


//================================================ RENAME TEXT INGAME ================================================\\

DWORD(BASE_REPLACE, OFS_REPLACE_STRING_1, STR_LASTWORD_XML, 0xE888 /*OFS E488*/, ((PBYTE)"Task", 5;
DWORD(BASE_REPLACE, OFS_REPLACE_STRING_1, STR_LASTWORD_XML, 0xE880 /*OFS E480*/, (PBYTE)"Quest", 6);
DWORD(BASE_REPLACE, OFS_REPLACE_STRING_1, STR_LASTWORD_XML, 0xEEE8 /*OFS EAE8*/, (PBYTE)"Harian (%d)", 12);
DWORD(BASE_REPLACE, OFS_REPLACE_STRING_1, STR_LASTWORD_XML, 0xEEC8 /*OFS EAC8*/, (PBYTE)"Montly (%d)", 14);
DWORD(BASE_REPLACE, OFS_REPLACE_STRING_1, STR_LASTWORD_XML, 0xEED8 /*OFS EAD8*/, (PBYTE)"Mingguan (%d)", 13);
DWORD(BASE_REPLACE, OFS_REPLACE_STRING_1, STR_LASTWORD_XML, 0xEF90 /*OFS EB90*/, (PBYTE)"LostSaga", 8);
DWORD(BASE_REPLACE, OFS_REPLACE_STRING_1, STR_LASTWORD_XML, 0xEF9C /*OFS EB9C*/, (PBYTE)"Waiting. . .", 13);